version: '3'

services:
    web:
        build:
            context: .
            dockerfile: Dockerfile-web
        depends_on:
            - db
        ports:
            - '8080:80'
        volumes:
            - ..:/var/www/html

    db:
        image: 'postgres:10.5'
        ports:
            - 4242:5432
        volumes:
            - ./postgres/data:/var/lib/postgresql/data/app_data:rw
            - ./postgres/config:/docker-entrypoint-initdb.d:rw
        environment:
            - POSTGRES_DB=mon-appart
            - POSTGRES_USER=mon-appart
            - POSTGRES_PASSWORD=pg_password
            - PGDATA=/var/lib/postgresql/data/app_data
