services:
    crawler.avendre_alouer:
        class:      Crawler\AVendreALouer
        arguments:  [ @crawler.search_url_builder.avendre_alouer]

    crawler.leboncoin:
        class:      Crawler\Leboncoin
        arguments:  [ @crawler.search_url_builder.leboncoin ]

    crawler.search_url_builder.leboncoin:
        class:  Crawler\LeboncoinSearchUrlBuilder
        public: false

    crawler.search_url_builder.avendre_alouer:
        class:  Crawler\AVendreALouerSearchUrlBuilder
        public: false
