services:
    listener.offers.fetched:
        class:      AppBundle\EventListener\OffersFetchedListener
        arguments:  [ @mailer, %alerts_destination_address%, %alerts_origin_address% ]
        tags:
            - { name: kernel.event_subscriber }
