home:
    path:         /
    defaults:     { _controller: AppBundle:Default:index }

star:
    path:         /star
    defaults:     { _controller: AppBundle:Default:star }

unstar:
    path:         /unstar
    defaults:     { _controller: AppBundle:Default:star, _unstar: true }

flag_offer_as_viewed:
    path:         /flag-as-viewed
    defaults:     { _controller: AppBundle:Default:flagAsView }

comment:
    path:         /comment
    defaults:     { _controller: AppBundle:Default:comment }
    requirements: { _method: POST }
