home:
    path:         /
    defaults:     { _controller: AppBundle:Default:index }

flag_offer_as_viewed:
    path:         /flag-as-viewed
    defaults:     { _controller: AppBundle:Default:flagAsView }
