home:
    path:         /
    defaults:     { _controller: AppBundle:Default:index }

comment:
    path:         /offers/{id}/comment
    defaults:     { _controller: AppBundle:Default:comment }
    requirements: { _method: POST }
    options:      { expose: true }

# API
api_offer_star:
    path:       /api/offers/{id}/star
    defaults:   { _controller: AppBundle:Api:star }
    options:    { expose: true }

api_offer_unstar:
    path:       /api/offers/{id}/unstar
    defaults:   { _controller: AppBundle:Api:star, _unstar: true }
    options:    { expose: true }

api_offer_flag_viewed:
    path:         /api/offers/{id}/flag-as-viewed
    defaults:     { _controller: AppBundle:Api:flagAsView }
    requirements: { _method: POST }
    options:      { expose: true }
